#!/bin/bash

# Redshift Manager, a yad based ui bash script for Redshift.
# Copyright (C) 2020  MLS Development (Michael L. Schaecher)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e

# This is used for the plug and key for notebook function of
# YAD, which is used for adding tabs to the YAD window.
key="${RANDOM}"

# User 12hr format for easier to understand.
hours=$(echo "1,2,3,4,5,6,7,8,9,10,11,12")

# Minutes of the hour.
minutes=$(echo "00,01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16
17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39
40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59" |
tr '\n' ',')

north_south="north,south"

east_west="east,west"

am_pm="am,pm"

management_type="time,location"

