#!/bin/bash

# Redshift Setup, a yad based bash script for Redshift
# Copyright (C) 2020  MLS Development (Michael L. Schaecher)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e

version="1.12"		# Keep version inline with redshift's version.

id=$(date +1%H%M%S)	# Plug id number for YAD notebook function.

# Default redshift-manager config file.
default_conf="/usr/share/doc/redshift-manager/default.conf"

home="/home/$(users)/.config"
redshift_manager_dir="${home}/redshift-manager"

# Since Redshift doesn't use standard bash it cannot be sourced, that
# is why a standard bash config file.
conf="${redshift_manager_dir}/default.conf"
redshift_conf="${home}/redshift.conf"

# Option for how to manage the redshift.conf file. Since location is
# disabled when dusk/dawn time is set, remove option from being edited.
#
manager_type="clock,location"

# User 12hr format for easier to understand.
hours=$(echo "1,2,3,4,5,6,7,8,9,10,11,12")

minutes=$(echo "00,01,02,03,04,05,06,07,08,09,10,11,12,13,14,15,16
17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39
40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59" |
tr '\n' ',')

# Link to Mozilla geoclue key.
geo="https://location.services.mozilla.com/v1/geolocate?key=geoclue"

north_south="north,south"

east_west="east,west"

# Source the redshift-manager config file
if [ ! -f ${conf} ] ; then
	mkdir -p ${redshift_manager_dir}
	cp -f ${default_conf} ${conf}
fi

source ${conf}

# Regardless if 'geoclue2' or 'manual' is the provider, the
# location is still enabled.
if [ "${manager}" == "clock" ] ; then
	manager="false"
else
	manager="true"
fi

# Determining the current 'dusk-time' that redshift is set to go to daylight
# hours the normal bash doesn't seem to work.

# Convert the 24 UTC time to 12hr am/pm.
if [ "${daytime_hour}" -gt "12" ] ; then
	daytime_hour=$(awk "BEGIN {print ${daytime_hour}-12}")
	daytime_pm="true"
else
	daytime_pm="false"
fi

# Convert the 24 UTC time to 12hr am/pm.
if [ "${nighttime_hour}" -gt "12" ] ; then
	nighttime_hour=$(awk "BEGIN {print ${nighttime_hour}-12}")
	nighttime_pm="true"
else
	daytime_pm="false"
fi

# Start daytime hours/minutes
a="^${daytime_hour}" && b="${daytime_hour}"
[ "${hours%$b*}" != "$hours" ] & daytime_hour="${hours%$b*}$a${hours#*$b}"

c="^${daytime_minutes}" && d="${daytime_minutes}"
[ "${minutes%$d*}" != "$minutes" ] & daytime_minutes="${minutes%$d*}$c${minutes#*$d}"
# End daytime hours/minutes

# Start nighttime hours/minutes
e="^${nighttime_hour}" && f="${nighttime_hour}"
[ "${hours%$f*}" != "$hours" ] & nighttime_hour="${hours%$f*}$e${hours#*$f}"

g="^${nighttime_minutes}" && h="${nighttime_minutes}"
[ "${minutes%$h*}" != "$minutes" ] & nighttime_minutes="${minutes%$h*}$g${minutes#*$h}"
# End nighttime hours/minutes

# Show the about page.
function redshift_manager_about () {

	yad --info --skip-taskbar --fixed --borders=24 --buttons-layout=center \
		--undecorated --center --text-align=center --title="About" \
		--text="$(cat data/about.xl)" \
		--button="gtk-close:0"


}

export -f redshift_manager_about

# YAD
yad --form --text-align=center --borders=24 --width=800 --height=480 \
	--fixed --window-icon=redshift --no-buttons --columns=4 --center \
	--separator="\n" --item-separator="," --title="Redshift Manager" \
	--field=" Transition:chk" ${transition} \
	--field="Temperature:lbl" "" \
	--field="Brightness:lbl" "" \
	--field=" Clock:chk"  ${clock} \
	--field="Daytime:lbl" "" \
	--field="Nighttime:lbl" "" \
	--field=" Location:chk" ${location} \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field="  PM   :chk" ${daytime_pm} \
	--field="  PM   :chk" ${nighttime_pm} \
	--field=" :lbl" "" \
	--field="  Auto :chk" ${auto_location} \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field="Daytime:scl"  ${transition_day} \
	--field="Daytime:scl" ${temp_day} \
	--field="Daytime:scl" $brightness_day} \
	--field=" :lbl" "" \
	--field="Hours:cb" ${daytime_hour} \
	--field="Hours:cb" ${nighttime_hour} \
	--field=" :lbl" "" \
	--field="Latitude:num" "${geoclue_latitude},0.00..90.00,0.01,2" \
	--field=":cb" ${north_south} \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field="gtk-about:btn" 'bash -c "redshift_manager_about"' \
	--field="Nighttime:scl"  ${transition_night} \
	--field="Nighttime:scl" ${temp_night} \
	--field="Nighttime:scl" $brightness_night} \
	--field=" :lbl" "" \
	--field="Minutes:cb" ${daytime_minutes} \
	--field="Minutes:cb" ${nighttime_minutes} \
	--field=" :lbl" "" \
	--field="Longitude:num" "${geoclue_longitude},0.00..180.00,0.01,2" \
	--field=":cb" ${east_west} \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field=" :lbl" "" \
	--field="gtk-ok:btn" "" \
