#!/bin/bash

# Create the need directories that are need fot building the
# package.
mkdir -p debian/${NAME} debian/${NAME}/${BIN} debian/${NAME}/${DOC}/${NAME} \
	debian/${NAME}/${APP} debian/${NAME}/${DIR} debian/${NAME}/DEBIAN

# Changelog
CHANGELOG=$(cat changelog)

COMMIT=$(cat .git/COMMIT_EDITMSG)

# Make sure that the commit message is not duplicated in then
# changelog.
if grep "* ${COMMIT}" changelog > /dev/null ; then
	cp changelog debian/changelog
else
cat <<EOF > debian/changelog
${NAME} (${VERSION}) ubuntu; urgency=medium

  * ${COMMIT}

 -- ${DEBFULLNAME} <${DEBEMAIL}>  $(date -R)

${CHANGELOG}
EOF
fi

cp -f debian/changelog changelog

# Avoid using cp to copy the main script because the version needs to be set.
if sed "21iVERSION=\"${VERSION}\"" scr/nightlight \
> debian/${NAME}/${BIN}/nightlight ; then

	cp -f scr/usr/share/redshift-manager/* debian/${NAME}/${DIR}/

	chmod 0755 debian/${NAME}/${BIN}/nightlight
	echo "installing:  debian/${NAME}/${BIN}/nightlight"
	chmod 0755 debian/${NAME}/${DIR}/set-clock
	echo "installing: debian/${NAME}/${DIR}/set-clock"
	chmod 0755 debian/${NAME}/${DIR}/set-location
	echo "installing: debian/${NAME}/${DIR}/set-location"

	if cp -f doc/about.xsl debian/${NAME}/${DIR}/about.xsl ; then

		echo "installing: debian/${NAME}/${DIR}"

		if cp -f LICENSE debian/${NAME}/${DOC}/${NAME}/copyright ; then
			echo "installing: debian/${NAME}/${DOC}/${NAME}/copyright"
		else
			echo "error: debian/${NAME}/${DOC}/${NAME}/copyright"
			exit 1
		fi

		if cp -f changelog debian/${NAME}/${DOC}/${NAME}/changelog ; then
			gzip -9 -f debian/${NAME}/${DOC}/${NAME}/changelog
			echo "installing: debian/${NAME}/${DOC}/${NAME}/changelog.gz"
		else
			echo "error: debian/${NAME}/${DOC}/${NAME}/changelog"
		fi

		if cp -f data/redshift-manager.desktop.ini debian/${NAME}/${APP}/redshift-manager.desktop ; then
			chmod 0755 debian/${NAME}/${APP}/redshift-manager.desktop
			echo "installing: debian/${NAME}/${APP}redshift-manager.desktop"
		else
			echo "error: debian/${NAME}/${APP}redshift-manager.desktop"
		fi

	else
		echo "error: debian/${NAME}/${DIR}"
		exit 1
	fi
else
	echo "error: debian/${NAME}/${BIN}/nightlight"
	exit 1

fi

# Generate a control file
cat <<EOF > debian/control
Source: ${NAME}
Section: networking
Priority: optional
Maintainer: ${DEBFULLNAME} <${DEBEMAIL}>
Build-Depends: cp, gzip, dpkg
Homepage: https://github.com/mschaecher78/redshfit-manager

Package:${NAME}
Architecture: all
Depends: redshift, redshift-gtk
Description: Manage Redshift backend utility
 Bash script using yad to provide a simple ui to manage and change redshift settings.
 .
 Features include setting daytime/nighttime temperatures and brightness, set redshift
 to use clock instead of location.
EOF

cd debian/${NAME}

find . -type f ! -path './DEBIAN/*' -printf '%P\0' | xargs -r0 md5sum > DEBIAN/md5sums

cd ../../

if dpkg-gencontrol -p${NAME} -P"debian/${NAME}" ; then
	dpkg-deb --build debian/${NAME} ..
fi